param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_branches:
  - architecture: cepf
    conv:
      - filters: 64
        kernel_size: 9
        activation: relu
    dense:
      - units: 9
        activation: softmax
    pooling:
      - pool_size: 27740
        strides: 1
  - architecture: cepf
    conv:
      - filters: 64
        kernel_size: 7
        activation: relu
    dense:
      - units: 9
        activation: softmax
    pooling:
      - pool_size: 27742
        strides: 1
    reshape:

param_consensus:
  units: 100
  activation: softmax

params_train:
  epochs: 10
  use_multiprocessing: True
