# Steves Resnet approach 10 v3 (branched)
# Can not be used for struct

param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_branches:
  - architecture: sdpf   # Using kernelsize 9 as first cnn
    conv:
      - filters: 64
        kernel_size: 5
        activation: relu
        padding: valid
        kernel_regularizer: l1
        strides: 5
    dense:
      - units: 512
        activation: relu
    dropouts:
      - rate: 0.5
    pooling:
      - pool_size: 4
        strides: 2
    skip:
      - filters: 8   # first skip
        kernel_size: 9
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid
  - architecture: sdpf   # Using kernelsize 5 as first cnn
    conv:
      - filters: 64
        kernel_size: 5
        activation: relu
        padding: valid
        kernel_regularizer: l1
        strides: 5  
    dense:
      - units: 512
        activation: relu
    dropouts:
      - rate: 0.5
    pooling:
      - pool_size: 4
        strides: 2
    skip:
      - filters: 8   # first skip
        kernel_size: 5
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid


params_consensus: #params for one dense layer
  units: 512
  activation: softmax
  kernel_regularizer: l1

params_train: # (for .fit)
  epochs: 80
  use_multiprocessing: True

params_train_for_compile: # (for .compile)
  learning_rate: 3e-4
  optimizer: adam