param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_train:
  epochs: 10
  use_multiprocessing: True

params_model:
  architecture: cdpcdpcpfee
  dropouts:
    - rate: .1
    - rate: .1
  pooling:
    - pool_size: 4
    - pool_size: 3
    - pool_size: 2
  conv:
    - filters: 16
      kernel_size: 9
      activation: relu
    - filters: 32
      kernel_size: 6
      activation: relu
      padding: same
    - filters: 64
      kernel_size: 4
      activation: relu
      padding: same
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax