# Initial Architecture with updated values on the basis of RNA "Zip Codes" length
param_dataLoader_train:
  batch_size: 32
  shuffle: True
  truncate: False

param_dataLoader_valid:
  batch_size: 32
  truncate: False

params_model:
  architecture: cpdcpdcpdfede
  learning_rate: 1e-4
  optimizer: nadam
  conv:
    - filters: 32
      kernel_size: 10
      activation: relu
    - filters: 32
      kernel_size: 10
      activation: relu
      padding: valid
    - filters: 32
      kernel_size: 10
      activation: relu
      padding: valid
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 3
    - pool_size: 3
    - pool_size: 3
  dropouts:
    - rate: 0.4
    - rate: 0.4
    - rate: 0.4
    - rate: 0.4
  #skip:
  #  - index: [0, 1]  # adding index
  #  - 0

params_train:
  epochs: 50
  use_multiprocessing: False

