param_dataLoader_train:
  padding_length:
  batch_size: 32,
  shuffle: True

param_dataLoader_valid:
  padding_length:
  batch_size: 32
  shuffle: True

params_model:
  conv:
    - filters: 64
      kernel_size: 9
      activation: reLU
  dense:
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 34518
      strides: 1

params_train:
  epochs: 10
  use_multiprocessing: True

