param_dataLoader_train:
  batch_size: 32
  shuffle: True
  struct: False

param_dataLoader_valid:
  batch_size: 32
  struct: False

params_model:
  architecture: cpfe
  conv:
    - filters: 64
      kernel_size: 9
      activation: relu
  dense:
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 34518
      strides: 1
  #skip:
  #  - index: [0, 1]  # adding index
  #  - 0



params_train:
  epochs: 3
  use_multiprocessing: True

