# Steves Resnet approach 9 (from net 8 but branched)
# Can also be used for STRUCT training

param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_branches:
  - architecture: sdpsdpfe   # Using kernelsize 9 as first cnn
    conv:
      - filters: 64
        kernel_size: 5
        activation: relu
        padding: valid
        kernel_regularizer: l1
        strides: 5
    dense:
      - units: 512
        activation: relu
    dropouts:
      - rate: 0.5
      - rate: 0.5
    pooling:
      - pool_size: 4
        strides: 2
      - pool_size: 4
        strides: 2
    skip:
      - filters: 24   # first skip
        kernel_size: 9
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid
      - filters: 48
        kernel_size: 9
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid
  - architecture: sdpsdpfe   # Using kernelsize 7 as first cnn
    conv:
      - filters: 64
        kernel_size: 5
        activation: relu
        padding: valid
        kernel_regularizer: l1
        strides: 5
    dense:
      - units: 512
        activation: relu
    dropouts:
      - rate: 0.5
      - rate: 0.5
    pooling:
      - pool_size: 4
        strides: 2
      - pool_size: 4
        strides: 2
    skip:
      - filters: 24   # first skip
        kernel_size: 5
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid
      - filters: 48
        kernel_size: 5
        activation: relu
        use_bn: True
        kernel_regularizer: l1
        padding: valid

params_consensus: #params for one dense layer
  units: 100
  activation: softmax

params_train:
  epochs: 80
  use_multiprocessing: True
  learning_rate: 1e-4
  optimizer: adam