# Steves Resnet approach 5
# Even Bigger and regularized version of Jonas net

param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_model:
  architecture: csdcsdcccccfee
  learning_rate: 1e-4
  optimizer: sgd
  conv:
    - filters: 16
      kernel_size: 11
      activation: relu
    - filters: 32
      kernel_size: 11
      activation: relu
      dilation_rate: 3   # from here dilators
    - filters: 1
      kernel_size: 11
      activation: relu
      dilation_rate: 7
    - filters: 1
      kernel_size: 11
      activation: relu
      dilation_rate: 17
    - filters: 1
      kernel_size: 11
      activation: relu
      dilation_rate: 39
    - filters: 1
      kernel_size: 11
      activation: relu
      dilation_rate: 71
    - filters: 1
      kernel_size: 11
      activation: relu
      dilation_rate: 191
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax
  dropouts:
    - rate: 0.5
    - rate: 0.5
  pooling:
    - pool_size: 4
      strides: 1
    - pool_size: 4
      strides: 1
  skip:
    - filters: 16   # first skip
      kernel_size: 11
      activation: relu
      use_bn: True
      kernel_regularizer: l1
    - filters: 32
      kernel_size: 11
      activation: relu
      use_bn: True
      kernel_regularizer: l1


params_train:
  epochs: 80
  use_multiprocessing: True

