param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_train:
  epochs: 10
  use_multiprocessing: True

params_model:
  architecture: 'cblcblpdcblcblpdcblcblpdcblcblpdaebleblee'
  dropouts:
    - { 'rate': .3 }
    - { 'rate': .3 }
    - { 'rate': .3 }
    - { 'rate': .3 }
    - { 'rate': .3 }
  pooling:
    - { 'pool_size': 2 }
    - { 'pool_size': 2 }
    - { 'pool_size': 2 }
    - { 'pool_size': 2 }
  conv:
    - { 'filters': 64, 'kernel_size': 7, 'activation': 'relu'}
    - { 'filters': 64, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 128, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 128, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 256, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 256, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 512, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
    - { 'filters': 512, 'kernel_size': 7, 'activation': 'relu', 'padding': 'same' }
  leaky:
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
    - {alfa: 0.05}
  dense:
    - {'units': 128, 'activation': 'softmax'}
    - {'units': 256, 'activation': 'softmax'}
    - {'units': 512, 'activation': 'softmax'}
    - {'units': 9, 'activation': 'softmax'}
  batch:
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
  attention:
    - {'num_heads': 5, 'key_dim': 80}