param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

params_model:
  architecture: cpdcpdfee
  dropouts:
    - rate: .2
    - rate: .2
  pooling:
    - pool_size: 4
    - pool_size: 4
  conv:
    - filters: 64
      kernel_size: 7
      activation: relu
      padding: valid
      use_bias: False
    - filters: 32
      kernel_size: 7
      activation: relu
      padding: valid
      use_bias: False
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax



params_train:
  epochs: 10
  use_multiprocessing: True

