params_dataLoader_train:
  batch_size: 32
  shuffle: True

params_dataLoader_valid:
  batch_size: 32

params_model:
  optimizer: nadam
  learning_rate: 1e-4
  architecture: cpdcpdfee
  dropouts:
    - rate: .5
    - rate: .5
  pooling:
    - pool_size: 4
    - pool_size: 4
  conv:
    - filters: 32
      kernel_size: 7
      activation: relu
      padding: valid
      use_bias: False
    - filters: 64
      kernel_size: 7
      activation: relu
      padding: valid
      use_bias: False
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax



params_train:
  epochs: 120
  use_multiprocessing: True

