param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32

param_consensus:
  units: 100
  activation: softmax

params_train:
  epochs: 10
  use_multiprocessing: True

params_branches:
  - architecture: ccpa
    conv: 
      - filters: 64
        kernel_size: 9
        padding: valid
        use_bias: False
      - filters: 32
        kernel_size: 9
        padding: valid
        use_bias: False
    pooling:
      - pool_size: 8
        strides: 8
    attention:
      - attention_size: 80
  - architecture: ccpa
    conv: 
      - filters: 64
        kernel_size: 20
        padding: valid
        use_bias: False
      - filters: 32
        kernel_size: 20
        padding: valid
        use_bias: False
    pooling:
      - pool_size: 8
        strides: 8
    attention:
      - attention_size: 80
  - architecture: ccpa
    conv: 
      - filters: 64
        kernel_size: 49
        padding: valid
        use_bias: False
      - filters: 32
        kernel_size: 49
        padding: valid
        use_bias: False
    pooling:
      - pool_size: 8
        strides: 8
    attention:
      - attention_size: 80
  
    
    
  