param_dataLoader_train:
  batch_size: 32
  shuffle: True
  struct: True

param_dataLoader_valid:
  batch_size: 32
  # Never set shuffle!!
  struct: True

params_model:
  learning_rate: 1e-3
  optimizer: nadam  # or adam

params_branches:
  - architecture: cscsdpa
    conv:
      - filters: 64
        kernel_size: 7
        activation: relu
        use_bias: False
        padding: valid
      - filters: 64
        kernel_size: 7
        activation: relu
        use_bias: False
        padding: valid
    pooling:
      - pool_size: 8
        strides: 8
    attention:
      - attention_size: 120
        reshape_size: 4314
    dropouts:
    - rate: 0.3
    skip:
      - filters: 64   # first skip
        kernel_size: 7
        activation: relu
        kernel_regularizer: l1
        use_bn: False
      - filters: 64
        kernel_size: 7
        activation: relu
        use_bn: False
        kernel_regularizer: l1
  - architecture: cscsdpa
    conv:
      - filters: 64
        kernel_size: 9
        activation: relu
        use_bias: False
        padding: valid
      - filters: 64
        kernel_size: 9
        activation: relu
        use_bias: False
        padding: valid
    pooling:
      - pool_size: 8
        strides: 8
    attention:
      - attention_size: 120
        reshape_size: 4313
    dropouts:
      - rate: 0.3
    skip:
      - filters: 64   # first skip
        kernel_size: 9
        activation: relu
        use_bn: False
        kernel_regularizer: l1
      - filters: 64
        kernel_size: 9
        activation: relu
        use_bn: False
        kernel_regularizer: l1

params_consensus: #params for one dense layer
  units: 100
  activation: softmax

params_train: #for compile method
  epochs: 10
  use_multiprocessing: True