param_dataLoader_train:
  batch_size: 32
  shuffle: True
  struct: True

param_dataLoader_valid:
  batch_size: 32
  # Never set shuffle
  struct: True

params_model:
  architecture: cscsdpaee
  learning_rate: 1e-5
  optimizer: nadam
  conv:
    - filters: 64
      kernel_size: 7
      activation: relu
      use_bias: False
      padding: valid
    - filters: 64
      kernel_size: 7
      activation: relu
      use_bias: False
      padding: valid
  dense:
    - units: 50
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 8
      strides: 8
  attention:
    - attention_size: 120
  dropouts:
    - rate: 0.3
  skip:
    - filters: 64   # first skip
      kernel_size: 11
      activation: relu
      use_bn: True
      kernel_regularizer: l1
    - filters: 64
      kernel_size: 11
      activation: relu
      use_bn: True
      kernel_regularizer: l1

params_train:
  epochs: 100
  use_multiprocessing: True