param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32
  # Never set shuffle

params_model:
  architecture: cccccdpebcdpebcdpeblcdpebcdpebcdpeblaee
  #learning_rate: 1e-4 
  optimizer: sgd
  conv:
    - filters: 16
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 32
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 64
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 128
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 256
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 128
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 64
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 32
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 16
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
    - filters: 8
      kernel_size: 7
      padding: valid
      use_bias: False
      kernel_regularizer: L1
  dense:
    - units: 256
      activation: relu
    - units: 128
      activation: relu
    - units: 64
      activation: relu
    - units: 32
      activation: relu
    - units: 16
      activation: relu
    - units: 8
      activation: relu
    - units: 64
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 2
      strides: 2
    - pool_size: 2
      strides: 2
    - pool_size: 2
      strides: 2
    - pool_size: 2
      strides: 2
    - pool_size: 2
      strides: 2
    - pool_size: 2
      strides: 2
  batch:
    - {}
    - {}
    - {}
    - {}
    - {}
    - {}
  dropouts:
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
  leaky:
    - alpha: 0.1
    - alpha: 0.1
  attention:
    - attention_size: 80

params_train:
  epochs: 1
  use_multiprocessing: True