param_dataLoader_train:
  batch_size: 32
  shuffle: True

param_dataLoader_valid:
  batch_size: 32
  # Never set shuffle

params_model:
  architecture: ccdpaee
  learning_rate: 1e-3
  optimizer: nadam
  conv:
    - filters: 64
      kernel_size: 9
      activation: relu
      use_bias: False
      padding: valid
    - filters: 64
      kernel_size: 9
      activation: relu
      use_bias: False
      padding: valid
  dense:
    - units: 50
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 8
      strides: 8
  attention:
    - attention_size: 120
  dropouts:
    - rate: 0.3

params_train:
  epochs: 100
  use_multiprocessing: True