param_dataLoader_train:
  batch_size: 128
  shuffle: True
  struct: True

param_dataLoader_valid:
  batch_size: 128
  # Never set shuffle
  struct: True

params_model:
  architecture: csdpfee
  learning_rate: 1e-5
  optimizer: nadam
  conv:
    - filters: 64
      kernel_size: 9
      activation: relu
      use_bias: False
      padding: same
  dense:
    - units: 50
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 4
  skip:
    - filters: 64 
      kernel_size: 9
      activation: relu
      padding: same
      use_bn: False
      specific_reg:
        kernel_regularizer:
          l1: 5e-5
          l2: 1e-4
        bias_regularizer:
          l2: 5e-5
        activity_regularizer:
          l2: 5e-5
      kernel_regularizer: l1
  dropouts:
    - rate: 0.5

params_train:
  epochs: 20
  use_multiprocessing: True