param_dataLoader_train:
  batch_size: 32
  shuffle: True
  struct: True

param_dataLoader_valid:
  batch_size: 32
  struct: True

params_model:
  architecture: cpdcpdcpdcpdcpdaede
  optimizer: nadam
  conv:
    - filters: 16
      kernel_size: 17
      activation: relu
    - filters: 32
      kernel_size: 15
      activation: relu
      padding: valid
    - filters: 64
      kernel_size: 11
      activation: relu
      padding: valid
    - filters: 96
      kernel_size: 9
      activation: relu
      padding: valid
    - filters: 128
      kernel_size: 7
      activation: relu
      padding: valid
  dense:
    - units: 512
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 4
    - pool_size: 4
    - pool_size: 4
    - pool_size: 4
    - pool_size: 4
  dropouts:
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
    - rate: 0.5
  attention:
    - attention_size: 120
      reshape_size: 31
  #skip:
  #  - index: [0, 1]  # adding index
  #  - 0

params_train:
  epochs: 20
  use_multiprocessing: False