# lernt nichts wirklich
optimization:
  optimizer: adam
  loss: categorical_crossentropy
  metrics:
    - accuracy
  epochs: 10
  learning_rate: 0.1
model:
 architecture: cdpcpfee
 dropouts:
   - .1
 pooling:
   - 3
   - 2
 conv_layers:
   -
      filters: 16
      kernel_size: 9
      activation: relu
   -
       filters: 64
       kernel_size: 6
       activation: relu
       padding: same
 dense_layers:
   -
    units: 256
    activation: relu
   -
    units: 9
    activation: softmax
