# origininating from flor_att8

param_dataLoader_train:
  batch_size: 32
  shuffle: True
  struct: True

param_dataLoader_valid:
  batch_size: 32
  # Never set shuffle
  struct: True


params_model:
  architecture: sdsdpaee
  learning_rate: 3e-5
  optimizer: nadam
  conv:
    - filters: 64
      kernel_size: 7
      activation: relu
      use_bias: True
      padding: valid
    - filters: 64
      kernel_size: 7
      activation: relu
      use_bias: True
      padding: valid
  dense:
    - units: 32
      activation: relu
    - units: 9
      activation: softmax
  pooling:
    - pool_size: 4
      strides: 4
  attention:
    - attention_size: 120
  dropouts:
    - rate: 0.5
    - rate: 0.5
  skip:
    - filters: 32   # first skip
      kernel_size: 11
      activation: relu
      use_bn: False
      kernel_regularizer: l1
    - filters: 32
      kernel_size: 11
      activation: relu
      use_bn: False
      kernel_regularizer: l1

params_train:
  epochs: 50
  use_multiprocessing: True